### ISSUE TITLE
Error while launching the admin web interface

### ISSUE THREAD

**Issue by TelaJulien** [j-easy/easy-jobs#28]
Hi,

When I try to run 
`java -cp "drivers/h2/*;lib/*" ^
 -Deasy.jobs.database.config.file=%cd%\conf\database.properties ^
 -Dserver.port=9000 ^
 org.jeasy.jobs.admin.Application`
I got 
`java.lang.IllegalArgumentException: Could not resolve placeholder 'application.version' in value "${application.version}"`
The server works fine but it's impossible to run the admin web interface.
I didn't make any modifications. I'm just trying to run the "demo" that you provide.
Did I miss something ?
BTW, java version is openjdk 1.8.0_171 on a debian 9.

Thanks

**Comment by benas** [comment]
Hi,

Thank you for reporting this issue! It took me sometime (and hairs!) to figure out the problem. The issue occurs with version `0.3` but not with version `0.3-SNAPHOT`.

The `application.version` property is defined in the `application.properties` files of the admin interface but not in the `application.properties` of the server. Both the admin and the server (along with their dependencies) are deployed in a single folder `lib`. When you run the startup command of the admin interface with version `0.3-SNAPSHOT`, it works fine. But when you do it with version `0.3` it fails because for some reason, the server's jar is loaded before the admin UI jar and hence the `application.version` property is not found.

Since the issue can arise with future versions, I separated the admin and server libs under `lib/admin` and `lib/server`. There will be some duplicate jars in the distribution file (which is what I wanted to avoid by putting both in the same folder) but this will be addressed in another issue.

Son basically what happened is: I tested with version `0.3-SNAPSHOT` and it was ok, I released version `0.3` and it does it work.. From now on, I will give a shot with the released version and write a end to end test for the distribution file. Other improvement I am considering is writing startup scripts for windows/unix and creating a docker image for each artifact.

Anyway, thank you for reporting the issue. I released version 0.4 for the matter. Could you please give it a try?

Thanks!

**Comment by benas** [comment]
BTW, I couldn't ask you to test with `0.4-SNAPSHOT` since the same issue may arise again. I had to release a version. So I'm closing this issue for now since it is tagged for 0.4 and will re-open it if necessary for `0.5`.
